services:
  prediction:
    build: 
      context: ./prediction
    image: prediction:latest
    container_name: prediction-instance
    volumes:
    - shared_data:/app/
    ports:
    - '8888:8888'
  fastapi:
    build: 
      context: ./api
    image: fast-api:latest
    depends_on:
      - prediction
    container_name: fastapi-instance
    volumes:
    - shared_data:/src/inputs/
    ports:
    - '8000:8000'
volumes:
  shared_data: